### ISSUE TITLE
Link spotify/apple account page

### ISSUE THREAD

**Issue by dhruv3745** [Purdue-ACM-SIGApp/mixtape-frontend#26] opened 2023-09-29 00:10 UTC
<img width="243" alt="Screenshot 2023-09-28 at 8 10 37 PM" src="https://github.com/Purdue-ACM-SIGAPP/mixtape-frontend/assets/36820900/20d1023b-af7f-4f05-90f4-a7a1c39ebaeb">

**Comment by alexkobus** [comment] 2023-09-29 00:12
duplicate of #25

**Closed as completed** 2023-09-29 00:11 UTC
